package io.github.ajaygodbole7.piitoken.runtime;

public enum StartupReason {
    GENERATED_OUTPUT_MISSING,
    GENERATED_OUTPUT_INVALID,
    JPA_MODEL_MISMATCH,
    SEARCHABLE_DIGESTS_PROHIBITED,
    CONFIGURATION_INVALID,
    PERSISTENCE_UNIT_COUNT_INVALID,
    HIBERNATE_INTERCEPTOR_CONFLICT,
    UNSAFE_BIND_LOGGING,
    REGISTRY_IO,
    TRANSACTION_MODE_INVALID,
    POLICY_ROW_MISSING,
    POLICY_IDENTITY_DRIFT,
    COMPILED_PROFILE_MISMATCH,
    MANIFEST_INTEGRITY,
    MANIFEST_INVALID,
    DESCRIPTOR_DRIFT,
    KEY_STATE_INVALID,
    KEY_MAPPING_DRIFT,
    PROVIDER_IDENTITY_DRIFT,
    PROVIDER_KEY_STATE_DRIFT,
    POLICY_INVALID
}
